version: "3.2"

services:
rsyncd:
  # You can also use tag dev
  image: zctmdc/inotify-rsync-server:latest
  environment:
    - USERNAME=zctmdc
    - PASSWORD=mysecret
  volumes:
    - nginx-conf-d:/data/nginx-conf-d/
    - sites-enabled:/data/sites-enabled/
    - acme-sh:/data/acme-sh/
  networks:
    - balanced
    # - nginx
  deploy:
    mode: global
    placement:
      constraints:
        - node.labels.es != true

inotify-rsyncd:
  # extends:
  #   service: rsyncd
  # will -> docker compose  -f .\rsyncd-stack.yaml config
  #     - node.labels.es != true
  #     - node.labels.es == true
  image: zctmdc/inotify-rsync-server:dev
  environment:
    - USERNAME=zctmdc
    - PASSWORD=mysecret
    - SERVICE_NAMES=rsyncd,syncd.example.com,127.0.0.1
  volumes:
    - nginx-conf-d:/data/nginx-conf-d/
    - sites-enabled:/data/sites-enabled/
    - acme-sh:/data/acme-sh/
  ports:
    - "873:873"
  networks:
    - balanced
    # - nginx
  deploy:
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - node.labels.es == true

volumes:
  sites-enabled:
  nginx-conf-d:
  acme-sh:
networks:
  balanced:
    driver: overlay
    attachable: true
  # nginx:
  #   external: true
  #   name: nginx_balanced
